### ISSUE TITLE
bad argument

### ISSUE THREAD

**Issue by goplanes** [KlobbenRillen/Young-Scripts#4]
...scripts\Young - BePrepared.lua:613: bad argument #1 to 'IsSameTeam' (userdata expected, got nil)

**Comment by goplanes** [comment]
By Asoji xDD

**Comment by goplanes** [comment]
+++++
...scripts\Young - BePrepared.lua:446: bad argument #3 to 'AddIcon' (vector expected, got nil)

**Comment by KlobbenRillen** [comment]
Do you downloaded the newest version? The lines you specified are outdated.

**Comment by goplanes** [comment]
i use last version. And you corrected lines 414 and 611, not these

**Comment by goplanes** [comment]
my bad))
